function dZdt = ZitaRHS(~, ZITA, Re, h, hq, U, V, G, Nx, Ny)

dZdt = zeros(Nx, Ny);

i = 2 : Nx-1;
j = 2 : Ny-1;
dZdt(i, j) = -0.5 * ( ...
                U(i+1, j) .* ZITA(i+1, j) - U(i-1, j) .* ZITA(i-1, j) + ...
                V(i, j+1) .* ZITA(i, j+1) - V(i, j-1) .* ZITA(i, j-1) + ...
                U(i,j) .* (ZITA(i+1, j) - ZITA(i-1, j)) + ...
                V(i, j) .* (ZITA(i, j+1) - ZITA(i, j-1)) ...
                ) / (2 * h) + ( ...
                ZITA(i+1, j) + ZITA(i-1, j) + ...
                    ZITA(i, j+1) + ZITA(i, j-1) - 4 * ZITA(i, j) ...
                ) / (Re * hq);

dZdt(G < 0) = 0;

end